### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Ygolova/progect-1#1]
1)
соответствия макету нет, проверять нечего
![image](https://github.com/Ygolova/progect-1/assets/8464662/c0f27a74-a282-48fd-8ad3-053275c2e1b4)
![image](https://github.com/Ygolova/progect-1/assets/8464662/2e0364ad-ca4f-4582-906c-df355ef44168)

2)
Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML / CSS, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://github.com/Ygolova/progect-1/assets/8464662/1d957c65-e87b-4a9f-b929-65e83f1f1e20)

3)
Обратите внимание на базовый кодстайл.
Для этого в самом начале курса вам предлагалось настроить и использовать editorconfig.

**Comment by Ygolova** [comment]
@Alecto Я делал через плагин Perfect Pixel и там все окей. Единственное, что не так, это то, что при увеличении ширины страницы оно не подгоняет размеры, а остается таким, каким оно было бы при полном размере. Я это менял только на 1920px, 992px, 768px, 576px. Это нужно исправить?

**Comment by Alecto** [comment]
Работа отсутствует, проверять нечего. Совпадений нет. Пересмотрите уроки, посмотрите как выполняется проверка.

**Comment by Ygolova** [comment]
@Alecto Обновил репозиторий и пейджс.

**Comment by Alecto** [comment]
Для сдачи проекта требуются две ссылки:
1 - на страницу github pages (конечный, видимый результат вашей работы).
2 - на страницу репозитория (ссылка на ваш профиль, на все репозитории -
ошибка).
Все описание есть в документации, в разделе "Критерии сдачи проекта".


пт, 26 трав. 2023 р. о 02:31 Yura Zaderigolova ***@***.***>
пише:

**Comment by Ygolova** [comment]
https://ygolova.github.io/progect-1/        pages 
https://github.com/Ygolova/progect-1        [repositories]

@Alecto

**Comment by Alecto** [comment]
4)
Внешний вид заполнителей не соответствует макету.
![image](https://github.com/Ygolova/progect-1/assets/8464662/4e86c074-44a1-4b17-9d25-e68fb8df1e13)


5)
иконка отсуствует
![image](https://github.com/Ygolova/progect-1/assets/8464662/478b6fc8-a469-402e-8be6-e2daecccffd7)


6)
вид меню некорректен
![image](https://github.com/Ygolova/progect-1/assets/8464662/4174cdc5-ec42-4505-a835-3b2ce1279443)


7)
не соответствует макету
![image](https://github.com/Ygolova/progect-1/assets/8464662/3c792175-5016-49f4-84e5-6cb06708fc36)


8)
внешний вид некорректен
![image](https://github.com/Ygolova/progect-1/assets/8464662/1e6e4eef-a9bc-4a20-b8cc-235fc6e917df)



далее работа не проверялась

**Comment by Alecto** [comment]
9)
название не установлено
![image](https://github.com/Ygolova/progect-1/assets/8464662/1405d33d-4301-4ae0-802b-cb837c8a20c4)

10)
на одном разрешении одни отступы, на другом - другие
![image](https://github.com/Ygolova/progect-1/assets/8464662/b4608162-3788-493e-b1e9-584e7806f3b6)
![image](https://github.com/Ygolova/progect-1/assets/8464662/a71e3d25-9ad5-4a7a-964f-0f8f380bf971)

11)
внешний вид некорректен
![image](https://github.com/Ygolova/progect-1/assets/8464662/c98b1855-fd76-4cbf-9ca1-9791a300961c)

12)
вендорные префиксы отсуствуют.
карта кода в стиле.
![image](https://github.com/Ygolova/progect-1/assets/8464662/f18924b4-3aa0-49c4-95cc-846b3b709a57)

14)
медиаправила неотсортированы и не сгруппированы
![image](https://github.com/Ygolova/progect-1/assets/8464662/cb2c0d21-3f54-4f17-aa9c-423a00275ef2)

**Comment by Alecto** [comment]
14 - не исправлено


15)
нормализатор в стиле остуствует

16)
внешний вид некорректен
![image](https://github.com/Ygolova/progect-1/assets/8464662/4053e4b2-83bb-4066-8f6e-f03d4d5b843d)


17)
внешний вид некорректен
![image](https://github.com/Ygolova/progect-1/assets/8464662/b55c7359-9ef9-46c7-9134-537c37ed94bf)


18)
внешний вид некорректен
![image](https://github.com/Ygolova/progect-1/assets/8464662/67dcd784-2d8c-457b-b088-d07474b746d9)


19)

Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://github.com/Ygolova/progect-1/assets/8464662/4e0fd3dd-b473-471a-919f-45ffd530851c)


20)
посмотрите где и как подключается jquery
![image](https://github.com/Ygolova/progect-1/assets/8464662/8dc3593c-7f33-4930-8d3e-7112a03711ba)



21)

Папки node_modules в сдаваемом проекте быть не должно.
Работа далее не проверялась.
Удалите ее, после чего работа над ошибками будет продолжена.

![image](https://github.com/Ygolova/progect-1/assets/8464662/04c14b7c-ce05-40e1-8af2-d6fa55c0f24d)

**Comment by Alecto** [comment]
14 - не исправлено
15 - не исправлено


22)
Правило * { ... } всегда пишется в начале кода (не требование синтаксиса, но настоятельная рекомендация).
![image](https://github.com/Ygolova/progect-1/assets/8464662/de89374b-d0a2-4142-83f5-09d1d987400e)

23)
типографику пишите в начале вашего стиля, после нормализации, перед классами
![image](https://github.com/Ygolova/progect-1/assets/8464662/35c65124-213c-46aa-90d2-af690520f347)


24)
внешний вид некорректен.
контент не по центру секции.
![image](https://github.com/Ygolova/progect-1/assets/8464662/18d33128-d0bc-4185-91e2-93d8a38840da)


25)
внешний вид некорректен.
![image](https://github.com/Ygolova/progect-1/assets/8464662/1895e3de-9b4e-4d39-b16e-66e6ed1d05d2)

26)
внешний вид некорректен.
![image](https://github.com/Ygolova/progect-1/assets/8464662/b08fed95-cb0b-4676-95d0-2e35124cd4cf)


более ответственно и внимательно отнеситесь к работе

**Comment by Ygolova** [comment]
@Alecto 
![image](https://github.com/Ygolova/progect-1/assets/132755937/106ccb6f-ed1a-4a17-8195-70b73ff70d2e)
![image](https://github.com/Ygolova/progect-1/assets/132755937/9420138c-1e5a-4a22-8724-e38af253c42f)
нормалайз же есть. Я не понимаю как отсортировать медиа правила. Я уже 2 раза их переделал. Что я делаю не так?

**Comment by Alecto** [comment]
> нормалайз же есть.
>
должен быть в стиле.


> Я не понимаю как отсортировать медиа правила. Я уже 2 раза их переделал.
> Что я делаю не там?
>
посмотрите уроки с 9 по 11 - показывал все

**Comment by Alecto** [comment]
12 - не исправлено
карта кода в конечном стиле, нет вендорных префиксов.

вроде последнее, что так и не исправили

**Comment by Ygolova** [comment]
@Alecto 
![image](https://github.com/Ygolova/progect-1/assets/132755937/c2b776c6-f83e-46d1-8c0d-91b47bdbc9cc)
![image](https://github.com/Ygolova/progect-1/assets/132755937/486afcf8-408b-46e3-9ead-23c4f1d9571e)


Так есть же вендоные префиксы. И что такое карта кода?

**Comment by Alecto** [comment]
нет.
карта кода присуствунт
[image: image.png]

вендорные префиксы отсуствуют
[image: image.png]

как на гитхаб по предоставленной ссылке
так и напрямую в проекте

[image: image.png]

пн, 5 черв. 2023 р. о 13:49 Yura Zaderigolova ***@***.***>
пише:

**Comment by Alecto** [comment]
без исправлений
![image](https://github.com/Ygolova/progect-1/assets/8464662/98d98834-7390-4dd3-b6ee-4c1158261857)

**Comment by Ygolova** [comment]
@Alecto я не понимаю что сделать(

**Comment by Ygolova** [comment]
@Alecto 
![image](https://github.com/Ygolova/progect-1/assets/132755937/62a3f132-8a98-4b59-85a9-6d23f78ea55f)
мне это убрать нужно или что? вендорные префиксы же есть

**Comment by Alecto** [comment]
напомню, что сейчас вы сдаете экзамен, я только проверяю и оцениваю вашу
работу.
вы можете попробовать исправить ошибки, можете оставить как есть.
хочу напомнить, что за каждую попытку сверх первых 3х снимается 10 штрафных
баллов - об этом неоднократно говорил на уроках.

вам нужно пересмотреть уроки с 8 по 11 включительно, где все эти моменты
были разобраны и показаны.
вы также, можете обсудить свои вопросы с группой.

вт, 6 черв. 2023 р. о 14:37 Yura Zaderigolova ***@***.***>
пише:
